server {
    listen 80;
    server_name devkobe-blog.com;
    server_tokens off;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # HTTP로 들어오면 -> HTTPS로 강제 이동
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name devkobe-blog.com;
    server_tokens off;

    # 인증서 경로 (아까 Certbot이 받아온 파일들)
    ssl_certificate /etc/letsencrypt/live/devkobe-blog.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/devkobe-blog.com/privkey.pem;
    
    # 보안 설정
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    # Spring Boot로 연결
    location / {
        proxy_pass http://blog-app:8080;
        proxy_set_header    Host                $http_host;
        proxy_set_header    X-Real-IP           $remote_addr;
        proxy_set_header    X-Forwarded-For     $proxy_add_x_forwarded_for;
    }
}
