version = 5.2.2
archive_dir = /etc/letsencrypt/archive/devkobe-blog.com
cert = /etc/letsencrypt/live/devkobe-blog.com/cert.pem
privkey = /etc/letsencrypt/live/devkobe-blog.com/privkey.pem
chain = /etc/letsencrypt/live/devkobe-blog.com/chain.pem
fullchain = /etc/letsencrypt/live/devkobe-blog.com/fullchain.pem
[renewalparams]
account = d0656b378eeaa8bb07f21158542bda9c
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
devkobe-blog.com = /var/www/certbot
